### ISSUE TITLE
glk_stream_open_file should silently return null on missing read file

### ISSUE THREAD

**Issue by erkyrath** [erkyrath/cheapglk#4]
This change will apply to all my interpreters. Keeping this open until they're all fixed. (Unless I decide to post duplicate bugs, but we'll see how long it takes me.)

**Comment by erkyrath** [comment]
Fixed in glkote.

**Comment by curiousdannii** [comment]
Thank you for also fixing the `glk_fileref_create_by_prompt` issue, I wasn't sure what to do with that.

glkterm does need the fixes, if you're still maintaining it.

**Comment by erkyrath** [comment]
glkterm... may be maintained again some time in the future.
