### ISSUE TITLE
Recursive call to gli_mktime on Win32

### ISSUE THREAD

**Issue by cspiegel** [erkyrath/cheapglk#8]
In `cgdate.c`, there is this:

```
#ifdef WIN32
#define mktime gli_mktime
```
Then later on:
```
#ifdef WIN32
time_t gli_mktime (struct tm * timeptr)
{
...
    time_t ret = mktime(timeptr) - offset;
}
```
But since `mktime` has been defined as `gli_mktime`, this will call itself instead of calling the standard library function.

The simplest fix may be:

```
#define mktime(tm) gli_mktime(tm)
...
time_t ret = (mktime)(timeptr) - offset;
```
to avoid macro expansion inside of `gli_mktime`.

**Comment by erkyrath** [comment]
Makes sense. Thanks.
